/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "outline": "#717786",
        "background": "#f0f2f8",
        "on-secondary": "#ffffff",
        "surface-bright": "#f0f2f8",
        "surface-container-low": "#e6eaf3",
        "on-secondary-fixed-variant": "#7201a2",
        "on-primary-container": "#fefcff",
        "primary-container": "#0070eb",
        "surface-tint": "#005bc1",
        "on-primary-fixed-variant": "#004493",
        "on-secondary-fixed": "#310048",
        "error": "#ba1a1a",
        "tertiary-fixed-dim": "#ffb3b5",
        "tertiary-container": "#e51245",
        "on-secondary-container": "#540079",
        "on-tertiary-container": "#fffbff",
        "secondary": "#8d2ebc",
        "on-surface": "#1a1b1f",
        "surface-container": "#e2e7f2",
        "surface-container-high": "#d9e0ef",
        "on-tertiary-fixed-variant": "#920027",
        "surface-container-highest": "#d0d9eb",
        "surface-dim": "#cbd4e8",
        "on-error-container": "#93000a",
        "secondary-fixed": "#f6d9ff",
        "on-primary-fixed": "#001a41",
        "tertiary-fixed": "#ffdada",
        "inverse-on-surface": "#f1f0f5",
        "primary-fixed-dim": "#adc6ff",
        "outline-variant": "#c1c6d7",
        "surface-variant": "#d9e0ef",
        "primary": "#0058bc",
        "on-surface-variant": "#414755",
        "error-container": "#ffdad6",
        "secondary-fixed-dim": "#e8b3ff",
        "on-error": "#ffffff",
        "inverse-surface": "#2f3034",
        "inverse-primary": "#adc6ff",
        "surface": "#f0f2f8",
        "primary-fixed": "#d8e2ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#40000c",
        "on-background": "#1a1b1f",
        "secondary-container": "#d072ff",
        "on-tertiary": "#ffffff",
        "tertiary": "#ba0034"
      },

      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "stack-lg": "24px",
        "container-padding": "20px",
        "margin-mobile": "20px",
        "gutter": "16px",
        "stack-sm": "8px",
        "stack-md": "16px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-xs": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}